DefaultContentLanguage = "pt-br"
title = "Tableless"
baseURL = "https://tableless.com.br/"
theme = "tableless"
SectionPagesMenu = "main"

disqusShortname = "tableless"
googleAnalytics = "UA-335027-1"

#enableRobotsTXT = "true"

[params]
    siteName = "Tableless"
    description = "Website com artigos e textos sobre Padrões Web, Design, Back-end e Front-end tudo em um só lugar. "

[permalinks]
    posts = "/:filename"
    pages = "/:filename"

[taxonomies]
    tag = "tags"
    category = "categories"
    author = "author"

[[menu.main]]
    name = "HTML"
    weight = -100
    identifier = "html"
    url = "/categories/html"
[[menu.main]]
    name = "CSS"
    weight = -99
    url = "/categories/css/"
[[menu.main]]
    name = "JavaScript"
    weight = -98
    url = "/categories/javascript/"
[[menu.main]]
    name = "Back-end"
    weight = -97
    url = "/categories/back-end/"
[[menu.main]]
    name = "WordPress"
    weight = -96
    url = "/categories/wordpress/"
[[menu.main]]
    name = "Design"
    weight = -95
    url = "/categories/design/"
[[menu.main]]
    name = "Acessibilidade"
    weight = -95
    url = "/categories/acessibilidade/"
[[menu.main]]
    name = "Na prática"
    weight = -94
    url = "/categories/técnicas-e-práticas/"
