DefaultContentLanguage = "pt-br"
title = "Tableless"
baseURL = "https://tableless.com.br/"
theme = "tableless"

disqusShortname = "tableless"
googleAnalytics = "UA-335027-1"

enableRobotsTXT = true
disableLiveReload = true

[params]
    siteName = "Tableless"
    description = "Website com artigos e textos sobre Padrões Web, Design, Back-end e Front-end tudo em um só lugar. "

[permalinks]
    posts = "/:filename"
    pages = "/:filename"

[taxonomies]
//    tag = "tags"
    category = "categories"
    author = "authors"


[related]
    threshold = 90
    includeNewer = false
    toLower = false

    [[related.indices]]
    name  = "categories"
    weight = 70
    [[related.indices]]
    name  = "author"
    toLower = true
    weight = 50
    [[related.indices]]
    name  = "title"
    weight = 30
    [[related.indices]]
    name  = "tags"
    weight = 20